import type { Metadata } from "next";
import { MainLayout } from "@/components/templates/MainLayout";
import { cn } from "@/lib/utils";
import { MainMobileLayout } from "@/components/templates/MainMobileLayout";
import "../../styles/globals.scss";
import { inter, jetbrains_mono } from "@/lib/fonts";
import type { LayoutProps } from "../../types/props";
import { languages } from "../i18n/settings";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((language) => ({ language }));
}

export default function RootLayout({ children, params }: LayoutProps) {
  return (
    <html lang={params.language} suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex bg-gray-50",
          inter.variable,
          jetbrains_mono.variable
        )}
      >
        <MainLayout params={params}>{children}</MainLayout>
        <MainMobileLayout params={params}>{children}</MainMobileLayout>
      </body>
    </html>
  );
}
